
-- First, let's add a comprehensive plant database with 100+ plants
INSERT INTO plant_species (name, scientific_name, watering_interval_days) VALUES
('🌵 Aloe Vera', 'Aloe barbadensis', 7),
('🌿 Snake Plant', 'Sansevieria trifasciata', 14),
('🌱 Spider Plant', 'Chlorophytum comosum', 5),
('🌹 Rose', 'Rosa rubiginosa', 3),
('🌿 Basil', 'Ocimum basilicum', 2),
('🌿 Mint', 'Mentha', 2),
('🌲 Fiddle Leaf Fig', 'Ficus lyrata', 7),
('🌵 Jade Plant', 'Crassula ovata', 10),
('🌸 Peace Lily', 'Spathiphyllum', 4),
('🌿 Pothos', 'Epipremnum aureum', 5),
('🌵 Rubber Plant', 'Ficus elastica', 7),
('🌺 Hibiscus', 'Hibiscus rosa-sinensis', 2),
('🌿 Monstera', 'Monstera deliciosa', 7),
('🌱 ZZ Plant', 'Zamioculcas zamiifolia', 14),
('🌸 Orchid', 'Orchidaceae', 7),
('🌿 Philodendron', 'Philodendron hederaceum', 5),
('🌵 Christmas Cactus', 'Schlumbergera', 10),
('🌿 English Ivy', 'Hedera helix', 3),
('🌱 Boston Fern', 'Nephrolepis exaltata', 3),
('🌸 African Violet', 'Saintpaulia', 4),
('🌿 Dracaena', 'Dracaena marginata', 7),
('🌵 Prickly Pear', 'Opuntia', 14),
('🌱 Calathea', 'Calathea ornata', 4),
('🌿 Rubber Tree', 'Ficus benghalensis', 7),
('🌸 Begonia', 'Begonia', 3),
('🌿 Parlor Palm', 'Chamaedorea elegans', 5),
('🌵 Barrel Cactus', 'Echinocactus grusonii', 21),
('🌱 Prayer Plant', 'Maranta leuconeura', 4),
('🌿 Swiss Cheese Plant', 'Monstera adansonii', 7),
('🌸 Geranium', 'Pelargonium', 3),
('🌿 Norfolk Pine', 'Araucaria heterophylla', 7),
('🌵 Haworthia', 'Haworthia fasciata', 10),
('🌱 Croton', 'Codiaeum variegatum', 4),
('🌿 Areca Palm', 'Dypsis lutescens', 5),
('🌸 Impatiens', 'Impatiens walleriana', 2),
('🌿 Weeping Fig', 'Ficus benjamina', 7),
('🌵 Echeveria', 'Echeveria elegans', 10),
('🌱 Dieffenbachia', 'Dieffenbachia seguine', 5),
('🌿 Majesty Palm', 'Ravenea rivularis', 5),
('🌸 Cyclamen', 'Cyclamen persicum', 4),
('🌿 Yucca', 'Yucca elephantipes', 10),
('🌵 String of Hearts', 'Ceropegia woodii', 7),
('🌱 Schefflera', 'Schefflera arboricola', 7),
('🌿 Kentia Palm', 'Howea forsteriana', 7),
('🌸 Azalea', 'Rhododendron', 3),
('🌿 Cast Iron Plant', 'Aspidistra elatior', 10),
('🌵 Ponytail Palm', 'Beaucarnea recurvata', 14),
('🌱 Chinese Evergreen', 'Aglaonema', 7),
('🌿 Bird of Paradise', 'Strelitzia reginae', 5),
('🌸 Petunia', 'Petunia', 2),
('🌿 Bamboo Palm', 'Chamaedorea seifrizii', 5),
('🌵 Crown of Thorns', 'Euphorbia milii', 7),
('🌱 Nerve Plant', 'Fittonia albivenis', 3),
('🌿 Lady Palm', 'Rhapis excelsa', 7),
('🌸 Pansy', 'Viola tricolor', 2),
('🌿 Dragon Tree', 'Dracaena draco', 10),
('🌵 Living Stones', 'Lithops', 21),
('🌱 Coleus', 'Solenostemon scutellarioides', 3),
('🌿 Fishtail Palm', 'Caryota mitis', 5),
('🌸 Marigold', 'Tagetes', 2),
('🌿 Corn Plant', 'Dracaena fragrans', 7),
('🌵 Hens and Chicks', 'Sempervivum tectorum', 10),
('🌱 Caladium', 'Caladium bicolor', 4),
('🌿 Date Palm', 'Phoenix canariensis', 7),
('🌸 Zinnia', 'Zinnia elegans', 2),
('🌿 Alocasia', 'Alocasia amazonica', 4),
('🌵 Desert Rose', 'Adenium obesum', 10),
('🌱 Anthurium', 'Anthurium andraeanum', 5),
('🌿 Coconut Palm', 'Cocos nucifera', 7),
('🌸 Sunflower', 'Helianthus annuus', 2),
('🌿 Bromeliad', 'Bromeliaceae', 7),
('🌵 Burro''s Tail', 'Sedum morganianum', 10),
('🌱 Ti Plant', 'Cordyline fruticosa', 5),
('🌿 Sago Palm', 'Cycas revoluta', 10),
('🌸 Lavender', 'Lavandula', 7),
('🌿 Hoya', 'Hoya carnosa', 7),
('🌵 String of Pearls', 'Senecio rowleyanus', 10),
('🌱 Peperomia', 'Peperomia obtusifolia', 7),
('🌿 Traveler''s Tree', 'Ravenala madagascariensis', 5),
('🌸 Dahlia', 'Dahlia pinnata', 3),
('🌿 Umbrella Tree', 'Schefflera actinophylla', 7),
('🌵 Paddle Plant', 'Kalanchoe luciae', 10),
('🌱 Wandering Jew', 'Tradescantia zebrina', 4),
('🌿 Canary Date Palm', 'Phoenix canariensis', 7),
('🌸 Carnation', 'Dianthus caryophyllus', 3),
('🌿 Staghorn Fern', 'Platycerium bifurcatum', 7),
('🌵 Ghost Plant', 'Graptopetalum paraguayense', 10),
('🌱 Rex Begonia', 'Begonia rex', 4),
('🌿 Windmill Palm', 'Trachycarpus fortunei', 7),
('🌸 Chrysanthemum', 'Chrysanthemum morifolium', 3),
('🌿 Tree Fern', 'Cyathea cooperi', 5),
('🌵 Moonstones', 'Pachyphytum oviferum', 10),
('🌱 Polka Dot Plant', 'Hypoestes phyllostachya', 3),
('🌿 Queen Palm', 'Syagrus romanzoffiana', 7),
('🌸 Iris', 'Iris germanica', 5),
('🌿 Maidenhair Fern', 'Adiantum capillus-veneris', 3),
('🌵 Blue Chalk Sticks', 'Senecio serpens', 10),
('🌱 Aluminum Plant', 'Pilea cadierei', 4),
('🌿 Mexican Fan Palm', 'Washingtonia robusta', 7),
('🌸 Tulip', 'Tulipa', 5),
('🌿 Rabbit Foot Fern', 'Davallia fejeensis', 4),
('🌵 Flaming Katy', 'Kalanchoe blossfeldiana', 7),
('🌱 Purple Passion', 'Gynura aurantiaca', 4),
('🌿 Bismarck Palm', 'Bismarckia nobilis', 10),
('🌸 Daffodil', 'Narcissus', 5),
('🌿 Holly Fern', 'Cyrtomium falcatum', 5),
('🌵 Panda Plant', 'Kalanchoe tomentosa', 10),
('🌱 Baby Tears', 'Soleirolia soleirolii', 2),
('🌿 Chilean Wine Palm', 'Jubaea chilensis', 14),
('🌸 Lily', 'Lilium', 5);
