// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfvmbtlomjzuszirzepv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdm1idGxvbWp6dXN6aXJ6ZXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzEwNTMsImV4cCI6MjA2NjI0NzA1M30.tYBXZEX72KHWJlFn6wBC1LuOEMguFQtJMRrCH4zdIp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);